---
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 6
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
  # '@typescript-eslint/explicit-function-return-type': off
  # '@typescript-eslint/prefer-regexp-exec': off
  # '@typescript-eslint/no-unused-vars': off
  # '@typescript-eslint/no-explicit-any': off
  # '@typescript-eslint/no-unsafe-call': warn
  # '@typescript-eslint/no-floating-promises': warn
